{% set name = "django-extra-views" %}
{% set version = "0.16.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://files.pythonhosted.org/packages/ac/61/c6d2ced11fc4235d2aeb422ad5af3b516effd942e2be5a263a5d93dcb1e2/django_extra_views-0.16.0.tar.gz
  sha256: 7f8e07bd6c9388816a7c08d752661172d4078758c2079fc0cadddfcf5cd38ae3
  
build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - django >=4.2
    - pip
    - python
  run:
    - django >=4.2
    - python

test:
  imports:
    - extra_views
    - extra_views.contrib

about:
  home: "https://github.com/AndrewIngram/django-extra-views"
  license: MIT
  license_family: MIT
  license_file: 
  summary: "Extra class-based views for Django"
  doc_url: https://django-extra-views.readthedocs.io/
  dev_url: https://github.com/AndrewIngram/django-extra-views

extra:
  recipe-maintainers:
    - https://github.com/gb119
