{% set name = "django-extra-views" %}
{% set version = "0.15.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git-url: https://github.com/AndrewIngram/django-extra-views.git
  git-rev: 571f5e2239467f16ce00ad544df8101edc969ed4
  
build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - django >=4.2
    - pip
    - python
  run:
    - django >=4.2
    - python

test:
  imports:
    - extra_views
    - extra_views.contrib

about:
  home: "https://github.com/AndrewIngram/django-extra-views"
  license: MIT
  license_family: MIT
  license_file: 
  summary: "Extra class-based views for Django"
  doc_url: https://django-extra-views.readthedocs.io/
  dev_url: https://github.com/AndrewIngram/django-extra-views

extra:
  recipe-maintainers:
    - https://github.com/gb119
